# fly.toml app configuration file generated for mantente-pb-final on 2025-10-21T09:28:36-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mantente-pb-final'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 8

  # fly.toml app configuration file generated for mantente-pb-final on 2025-10-21T09:28:36-04:00
# ... [rest of the file] ...

# 🚨 AÑADE ESTA SECCIÓN ABAJO DEL TODO 🚨
[mounts]
  # Nombre del volumen que creaste/crearás con flyctl volumes create
  source="mantente_final_data"
  # La ruta interna de PocketBase donde guarda los datos
  destination="/pb/pb_data"
