# fly.toml app configuration file generated for mantente-pb-clean on 2025-10-21T10:01:10-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mantente-pb-clean'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source="pocketbase_data" 
  destination="/pb/pb_data"