FROM alpine:latest

RUN apk add --no-cache \
    ca-certificates \
    curl

WORKDIR /app

COPY pocketbase /usr/local/bin/pocketbase
RUN chmod +x /usr/local/bin/pocketbase

EXPOSE 8090

CMD ["pocketbase", "serve", "--http=0.0.0.0:8090"]
